# In seconds.
daily-interval: 86400
completed-interval: 43200

# In ticks.
title-duration:
  fade-in: 20
  stay: 100
  fade-out: 20

objectives:
  kill_animal:
    min: 10
    max: 15
    prize: 45.0
  kill_monster:
    min: 16
    max: 32
    prize: 60.0
  break_block:
    min: 32
    max: 64
    prize: 16.0
  enchant:
    min: 3
    max: 9
    prize: 60.0
  fish:
    min: 6
    max: 10
    prize: 100.0
  visit_biome:
    min: 1
    max: 1
    prize: 750.0
  craft:
    min: 16
    max: 32
    prize: 10.0
  smelt:
    min: 32
    max: 64
    prize: 10.0
  cook:
    min: 32
    max: 64
    prize: 16.0
  tame:
    min: 8
    max: 16
    prize: 40.0
  harvest:
    min: 64
    max: 128
    prize: 10.0

multipliers:
  materials:
    ancient_debris: 6.0
    diamond: 7.0
    iron: 3.0
    gold: 5.0
    lapis_lazuli: 2.0
    wheat: 1.2
    chorus_fruit: 1.5
    carrot: 0.8
    axe: 3.0
    sword: 2.0
    helmet: 5.0
    chestplate: 8.0
    leggings: 7.0
    boots: 4.0
    book: 3.0
    quartz: 1.5
    chainmail: 4.0
  entities:
    vindicator: 2.0
    iron_golem: 5.0
    ravager: 5.0
    chicken: 0.5

# This blacklists based on if the material or entity contains a part of or all of the string in the blacklist.
blacklist:
  materials:
    - glazed
    - anvil
    - template
    - bedrock
    - stripped
    - barrier
    - structure
    - sign
    - rail
    - armor_stand
    - button
    - door
    - pressure_plate
    - glass_pane
    - spawn_egg
    - cartography_table
    - netherite
    - diamond
    - clock
    - command_block
    - crafter
    - stairs
    - trapdoor
    - crying_obsidian
    - hoe
    - sword
    - axe
    - leggings
    - shovel
    - disc
    - elytra
    - banner_pattern
    - ghast_tear
    - pickaxe
    - hay_block
    - hopper
    - jukebox
    - jigsaw
    - knowledge_book
    - lava
    - lead
    - shulker
    - ominous_trial_key
    - froglight
    - rail
    - armor_trim
    - void_air
    - vault
    - wet_sponge
    - bundle
    - dried_kelp
    - sniffer_egg
    - cracked
  entities:
    - elder_guardian
    - ender_dragon
    - wither
    - warden
    - creaking
    - breeze_wind_charge
    - ominous_item_spawner
    - breeze
    - end_crystal
    - evoker_fangs
    - eye_of_ender
    - giant
    - interaction
    - leash_knot
    - llama_spit
    - marker
    - minecart
    - player
    - shulker_bullet
    - stray
    - wither_skull
    - painting
    - item
    - fishing_bobber
    - experience_orb
    - area_effect_cloud
    - glow_item_frame
    - falling_block
    - boat
    - mule
    - donkey
    - skeleton_horse
    - zombie_horse
  custom-fishing:
    - book
    - stick
    - rod
    - diamond
    - fishfinder
    - flint
    - kelp
    - nether_brick
    - obsidian
    - shoes
    - stone
    - water_effect
    - lava_effect
    - bait
    - vanilla
    - seagrass
    - gold_ingot
    - gold_nugget
    - golden_star
    - silver_star
    - netherrack
    - hook
  biomes:
    - advanced
    - cave/
    - minecraft
    - nullscape

reroll-price: 200
single-price: 25

# Make sure these currency names are valid in CoinsEngine!
currency:
  prize: silver
  reroll: gold
