# In hours
daily-interval: 86400

objectives:
  kill_animal:
    min: 32
    max: 64
    prize: 4.0
  kill_monster:
    min: 32
    max: 64
    prize: 10.0
  break_block:
    min: 32
    max: 64
    prize: 8.0
  enchant:
    min: 1
    max: 3
    prize: 500.0
  fish:
    min: 10
    max: 20
    prize: 20.0
  visit_biome:
    min: 1
    max: 1
    prize: 500.0
  craft:
    min: 6
    max: 12
    prize: 20.0
  smelt:
    min: 6
    max: 12
    prize: 40.0
  cook:
    min: 32
    max: 64
    prize: 6.0
  tame:
    min: 16
    max: 64
    prize: 10.0
  harvest:
    min: 64
    max: 128
    prize: 2.0

reroll-price: 200

currency:
  prize: silver
  reroll: gold
