# In hours
daily-interval: 86400
completed-interval: 43200

# In ticks.
title-duration:
  fade-in: 20
  stay: 100
  fade-out: 20

objectives:
  kill_animal:
    min: 32
    max: 64
    prize: 15.0
  kill_monster:
    min: 32
    max: 64
    prize: 30.0
  break_block:
    min: 32
    max: 64
    prize: 8.0
  enchant:
    min: 1
    max: 3
    prize: 15.0
  fish:
    min: 10
    max: 20
    prize: 30.0
  visit_biome:
    min: 1
    max: 1
    prize: 750.0
  craft:
    min: 16
    max: 32
    prize: 5.0
  smelt:
    min: 32
    max: 64
    prize: 5.0
  cook:
    min: 32
    max: 64
    prize: 8.0
  tame:
    min: 16
    max: 32
    prize: 8.0
  harvest:
    min: 64
    max: 128
    prize: 5.0

multipliers:
  materials:
    ancient_debris: 6.0
    netherite: 104.0
    diamond: 13.0
    iron: 3.0
    gold: 5.0
    leather: 3.0
    lapis_lazuli: 2.0
    wheat: 1.2
    chorus_fruit: 1.5
    carrot: 0.8
    axe: 3.0
    sword: 2.0
    helmet: 5.0
    chestplate: 8.0
    leggings: 7.0
    boots: 4.0
    book: 3.0
    trident: 208.0
    elytra: 220.0
    quartz: 1.5
    chainmail: 4.0
    shulker_box: 50.0
  entities:
    vindicator: 2.0
    iron_golem: 5.0
    ravager: 5.0
    chicken: 0.5

# This blacklists based on if the material or entity contains a part of or all of the string in the blacklist.
blacklist:
  materials:
    - glazed
    - anvil
    - template
    - stripped
  entities:
    - elder_guardian
    - ender_dragon
    - wither
  custom-fishing:
    - book
    - stick
    - rod
    - diamond
    - fishfinder
    - flint
    - kelp
    - nether_brick
    - obsidian
    - shoes
    - stone
    - water_effect
    - lava_effect
    - bait
    - vanilla
    - seagrass
    - gold_ingot
    - golden_star
    - silver_star

reroll-price: 200
single-price: 25

# Make sure these currency names are valid in CoinsEngine!
currency:
  prize: silver
  reroll: gold
